# Generated by Django 5.0.4 on 2024-04-29 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileName', models.CharField(max_length=200)),
                ('ProfilePrice', models.IntegerField()),
                ('ProfileDelivery', models.CharField(blank=True, max_length=100, null=True)),
                ('ProfileDescription', models.TextField(blank=True, null=True)),
                ('ProfilVisibility', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'business_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=255, null=True)),
                ('RegisteredName', models.CharField(max_length=255, null=True)),
                ('RegistrationNumber', models.CharField(max_length=50, null=True)),
                ('UENIssueDate', models.DateField(null=True)),
                ('UENStatus', models.CharField(max_length=100, null=True)),
                ('LegalEntityType', models.CharField(max_length=50, null=True)),
                ('LegalEntityTypeSuffix', models.CharField(max_length=50, null=True)),
                ('Town', models.CharField(max_length=100, null=True)),
                ('CreatedAt', models.DateTimeField(null=True)),
                ('UpdatedAt', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SampleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReportTitle', models.CharField(max_length=200)),
                ('ReportUrl', models.CharField(blank=True, max_length=500, null=True)),
                ('ReportVisibility', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'sample_reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SitesNames',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('ssl', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sites_names',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SitesVariables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sites_variables',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SitesSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sitesnames')),
                ('site_variable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sitesvariables')),
            ],
            options={
                'db_table': 'sites_settings',
                'managed': True,
            },
        ),
    ]
